### PR TITLE
Add Config Examples section

### LINKED ISSUE #20: Config + Code Examples in Readme
Hi @Sec-ant , thanks for the great Prettier plugin! (and thanks @JounQin for [`prettier-plugin-sql`](https://github.com/un-ts/prettier/tree/master/packages/sql), which also enables the formatting of SQL tagged template literals!)

Would be great to see a few complete config examples like the config code examples in comments in https://github.com/Sec-ant/prettier-plugin-embed/issues/16

Either:

A) full interactive examples (eg. CodeSandbox) or "recipes"
B) including configuration and code as in below

`prettier.config.js`

```js
/** @type {import('prettier').Config} */
const prettierConfig = {
  plugins: ['prettier-plugin-embed', 'prettier-plugin-sql'],
};

/** @type {import('prettier-plugin-embed').PrettierPluginEmbedOptions} */
const prettierPluginEmbedConfig = {
  embeddedSqlIdentifiers: ['sql'],
}

/** @type {import('prettier-plugin-sql').SqlBaseOptions} */
const prettierPluginSqlConfig = {
  language: 'postgresql',
  keywordCase: 'upper',
}

const config = {
  ...prettierConfig,
  ...prettierPluginEmbedConfig,
  ...prettierPluginSqlConfig,
};

export default config;
```

`index.ts` (before)

```js
const animals = await sql`
      SELECT
*                 
                       FROM
       animals
`;
```

`index.ts` (after)

```js
const animals = await sql`
  SELECT
    *                 
  FROM
    animals
`;
```

### PR DESCRIPTION
**Pull request by karlhorky**
Closes #20

- [x] Move philosophy section down below options
- [x] Add Config Examples section with `prettier-plugin-sql` example

### CODE REVIEW

**Comment by Sec-ant** [comment]
Thanks very much. @karlhorky

Sorry I've been occupied by some real life stuff this week and haven't got time to push further some of the things we've discussed recently. I'll make some time later today or tomorrow to address all of these things.

**Comment by Sec-ant** [comment]
@karlhorky Hi there, I prefer to move the config examples to a dedicated markdown file so I just edited on your PR, I hope it's fine with you.

I will merge this for now and steer my focus more on the new language support, tests and code refactoring for the following weeks. But I'll get back to the config examples when most of the codebase and APIs are stable.

Thanks for the help!

**Comment by karlhorky** [comment]
Glad to help, thanks for the review and merge!

**Comment by Sec-ant** [comment]
I just found out the [all-contributors](https://allcontributors.org/) bot so let's have a test :D

@all-contributors please add [karlhorky](https://github.com/karlhorky) for code and doc

**Comment by Sec-ant** [comment]
I just found out the [all-contributors](https://allcontributors.org/) bot so let's have a test :D

@all-contributors please add @karlhorky for code and doc

**Pull request merged**
